// STEP/DIR stepper control for 1..6 axes (spec §7.2, §12, §13).
//
// On the ESP32 the step pulses are generated by the FastAccelStepper hardware
// engine (RMT / MCPWM + timer), NOT from loop(), so timing is deterministic and
// independent of Wi-Fi / web / I²C latency. FastAccelStepper also does the
// trapezoidal accel/decel in hardware (fed from maxSpeedMmS / maxAccelMmS2);
// the pure MotionPlanner remains the host-tested reference model. Homing uses
// runForward/runBackward for the seeks and moveTo for the back-off/offset.
#pragma once

#include <cstdint>
#include <vector>

#include "../../core/motion/MotionPlanner.h"
#include "../../core/motion/StepperAxis.h"
#include "../../core/util/Debounce.h"

#if defined(ARDUINO)
#include <Arduino.h>
#include <FastAccelStepper.h>
#endif

namespace gmb {

struct AxisPins {
    int8_t step = -1;
    int8_t dir = -1;
    int8_t home = -1;
    int8_t limit = -1;
};

class StepperBank {
public:
    // `homeActiveHigh[i]` gives the sensor polarity for axis i (from its homing
    // config). homeActive()/limitActive() are normalised through it; empty means
    // active-low (the common endstop wiring).
    void begin(const std::vector<AxisConfig>& axes,
               const std::vector<AxisPins>& pins, int8_t enablePin,
               const std::vector<bool>& homeActiveHigh = {},
               const std::vector<bool>& limitActiveHigh = {});

    // Sample & debounce the HOME/LIMIT inputs. Call once per loop() before
    // reading homeActive()/limitActive()/homeRawHigh().
    void updateSensors(uint32_t nowMs);

    void enableDrivers(bool on);
    bool enabled() const { return enabled_; }

    // Position-mode move to an absolute target (mm, soft-limited).
    void moveToMm(size_t axis, double mm);
    // Same but without soft-limit clamping (used during homing).
    void moveToMmRaw(size_t axis, double mm);
    // Velocity-mode cruise at a signed speed (mm/s), used by homing seeks.
    void setVelocityMm(size_t axis, double mmS);
    void stop(size_t axis);          // decelerated stop (normal musical stop)
    void emergencyStop(size_t axis); // immediate hard stop (LIMIT / E-stop)
    void stopAll();

    // Redefine the current physical position as `mm` (homing anchors home = 0).
    void setPositionReference(size_t axis, double mm);

    double positionMm(size_t axis) const;
    bool atTarget(size_t axis) const;   // motor stopped (used for "is it still?")
    // Stopped AND actually within tolerance of the last commanded position move —
    // a refused/interrupted move does not count as "arrived at the fret".
    bool reachedTarget(size_t axis) const;
    bool isRunning(size_t axis) const;  // true while the step engine is moving
    bool homeActive(size_t axis) const;   // normalised active-low reading
    bool homeRawHigh(size_t axis) const;  // raw level (polarity-aware homing)
    bool limitActive(size_t axis) const;

    // True if any ENABLED axis could not attach a hardware step generator.
    bool attachFault() const { return attachFault_; }
    // Per-axis attach fault (a disabled axis is never faulted here).
    bool axisAttachFault(size_t axis) const {
        return axis < axes_.size() && axes_[axis].attachFault;
    }

    // No-op on hardware (engine generates steps); kept for interface symmetry.
    void tick(uint32_t nowUs) { (void)nowUs; }

    size_t count() const { return axes_.size(); }

private:
    struct AxisRt {
        StepperAxis geom;
        AxisPins pins;
        double stepsPerMm = 80.0;
        long position = 0;  // used by the non-Arduino stub only
        double cmdTargetMm = 0.0;  // last commanded position-move target
        bool hasTarget = false;
        bool homeActiveHigh = false;
        bool limitActiveHigh = false;
        bool attachFault = false;  // this enabled axis could not attach a generator
        Debouncer homeDeb;   // debounced raw HIGH level of the HOME pin
        Debouncer limitDeb;  // debounced raw HIGH level of the LIMIT pin
        AxisRt(const AxisConfig& c) : geom(c) {}
    };
    std::vector<AxisRt> axes_;
    int8_t enablePin_ = -1;
    bool enabled_ = false;
    bool attachFault_ = false;

#if defined(ARDUINO)
    FastAccelStepperEngine engine_;
    std::vector<FastAccelStepper*> steppers_;
#endif
};

}  // namespace gmb
